backend:
  name: git-gateway
  branch: gh-pages

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Index"
        name: "index"
        fields:
          - {label: "HTML", name: "body", widget: "code", default_language: "html"}
